service:
  name: dojo-serverless-backend

package:
  exclude:
    - .git/**
    - .gitignore

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev
  profile: dojo-serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:ListStreams
      Resource:
        - 'Fn::GetAtt': [DojoServerlessTable, Arn]
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  hello:
    handler: hello.main
    events:
      - http:
          method: get
          path: hello
          cors: true
  createVirus:
    handler: src/handlers/virus/create.main
    events:
      - http:
          method: post
          path: virus
          cors: true
      - schedule: rate(1 minute)
  getVirus:
    handler: src/handlers/virus/get.main
    events:
      - http:
          method: get
          path: virus
          cors: true
  killVirus:
    handler: src/handlers/virus/kill.main
    events:
      - http:
          method: delete
          path: virus/{id}
          cors: true
  connectWebsocket:
    handler: src/handlers/real-time/connect.main
    events:
      - websocket:
          route: '$connect'
  disconnectWebsocket:
    handler: src/handlers/real-time/disconnect.main
    events:
      - websocket:
          route: '$disconnect'
  sendMessageToClient:
    handler: src/handlers/real-time/sendMessageToClient.main
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [DojoServerlessTable, StreamArn]

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb.yml)}
