service:
  name: dojo-serverless-backend

package:
  exclude:
    - .git/**
    - .gitignore

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev
  profile: dojo-serverless
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  hello:
    handler: hello.main
    events:
      - http:
          method: post
          path: virus

resources:
  - ${file(resources/api-gateway-errors.yml)}
