service:
  name: dojo-serverless-backend

package:
  exclude:
    - .git/**
    - .gitignore

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  createVirus:
    handler: src/handlers/createVirus.main
    events:
      - http:
          method: post
          path: virus
  getVirus:
    handler: src/handlers/getVirus.main
    events:
      - http:
          method: get
          path: virus
  killVirus:
    handler: src/handlers/killVirus.main
    events:
      - http:
          method: delete
          path: virus/:id

resources:
  - ${file(resources/api-gateway-errors.yml)}
