Resources:
  DojoServerlessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dojo-serverless-table
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
